default_platform(:ios)

platform :ios do
  desc "deploy beta to appstore"
  lane :beta do
    build_app(scheme: "fastlane-sample", xcargs: "-allowProvisioningUpdates")

    api_key = app_store_connect_api_key(
      key_id: "FF9M3UX5LN",
      issuer_id: "1158e62a-2a94-4b61-8cb1-ced7de58368e",
      key_filepath: "~/private_keys/AuthKey_FF9M3UX5LN.p8",
      duration: 180,
      in_house: false
    )

    upload_to_testflight(api_key: api_key)
  end
end


desc "register devices"
lane :register_new_devices do
  # see the Apple Sample (http://devimages.apple.com/downloads/devices/Multiple-Upload-Samples.zip)
  register_devices(
    devices_file: "./fastlane/devices.txt",
    team_id: "YFYG54KA39"
  )
  match_after_register
end

desc "match_after_register"
lane :match_after_register do
  match(type: "development", force_for_new_devices: true)
end