default_platform(:ios)

platform :ios do
  desc "deploy beta to appstore"
  lane :beta do

    Dir.glob("Applications/")

    puts ENV["DEVELOPER_DIR"]

    xcversion(version: "13.2.1")

    create_keychain(
      name: "ohtaki",
      password: "19990220",
      timeout: 1800
    )

    api_key = app_store_connect_api_key(
      key_id: "HU2JCWXK59",
      issuer_id: "1158e62a-2a94-4b61-8cb1-ced7de58368e",
      key_content: "-----BEGIN PRIVATE KEY-----\nMIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQggmuRaSFYZIGkuU1t
      KCGnahJuJ21b7sNav43CKxDUg3GgCgYIKoZIzj0DAQehRANCAAQVvQETT0KwT68X
      wWSd+xhF0lsq8RTE9RKn0Qa/8BPwHqIA0PqS4TgZxJzBMlzn6YhirC6aCDKuxu7G
      6he5VehI\n-----END PRIVATE KEY-----",
      duration: 180,
      in_house: false
    )

    personal_access_token = ENV["PERSONAL_GITHUB_ACCESS_TOKEN"]
    authorization_token_str = "HikaruOhtaki:#{personal_access_token}"

    update_code_signing_settings(
      use_automatic_signing: false,
      path: "fastlane-sample.xcodeproj",
      targets: "fastlane-sample",
      team_id: "YFYG54KA39",
      code_sign_identity: "iPhone Distribution",
      bundle_identifier: "ohtaki.fastlane-sample",
      profile_name: "match AppStore ohtaki.fastlane-sample",
    )

    update_code_signing_settings(
      use_automatic_signing: false,
      path: "fastlane-sample.xcodeproj",
      targets: "NotificationService",
      team_id: "YFYG54KA39",
      code_sign_identity: "iPhone Distribution",
      bundle_identifier: "ohtaki.fastlane-sample.NotificationService",
      profile_name: "match AppStore ohtaki.fastlane-sample.NotificationService",
    )


    match(
      git_basic_authorization: Base64.strict_encode64(authorization_token_str),
      api_key: api_key,
      app_identifier: ["ohtaki.fastlane-sample", "ohtaki.fastlane-sample.NotificationService"],
      type: "appstore",
      readonly: true,
      keychain_name: "ohtaki",
      keychain_password: "19990220",
    )

    build_app(scheme: "fastlane-sample")

    upload_to_testflight(
      api_key: api_key,
      changelog: "This is my changelog of things that have changed in a log",
      skip_waiting_for_build_processing: true
    )
  end
end


desc "register devices"
lane :register_new_devices do
  register_devices(
    devices_file: "./fastlane/devices.txt",
    team_id: "YFYG54KA39"
  )
  match_after_register
end

desc "match_after_register"
lane :match_after_register do
  match(type: "development", force_for_new_devices: true)
end
