name: CICD

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v2
      - name: Deploy Testflight
        env:
          MATCH_KEYCHAIN_NAME: "KEYCHAIN"
          MATCH_KEYCHAIN_PASSWORD: "19990220"
          PERSONAL_GITHUB_ACCESS_TOKEN: "${{ secrets.PERSONAL_GITHUB_ACCESS_TOKEN }}"
          USERNAME: "HikaruOhtaki"
          MATCH_PASSWORD: '${{ secrets.MATCH_PASSWORD }}'
        run: |
          echo "$(ls /Users/runner/Library/Developer/)"
          fastlane beta
