name: CI

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v2

      - name: create AppStoreConnect AuthKey
        run: |
          mkdir ~/private_keys; echo "${{ secrets.ASC_API_KEY }}" | base64 -d > ~/private_keys/AuthKey_$ASC_KEY_ID.p8
          
      - name: Deploy Testflight
        run: fastlane beta
