name: CICD

on:
  workflow_dispatch:

env:
  DEVELOPER_DIR: /Applications/Xcode_13.2.1.app

jobs:
  build:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v2
      - name: Select Xcode version
        run: sudo xcode-select -s '/Applications/Xcode_13.1.app/Contents/Developer'
      - name: Show Xcode version
        run: xcodebuild -version
      - name: Deploy Testflight
        env:
          MATCH_KEYCHAIN_NAME: "KEYCHAIN"
          MATCH_KEYCHAIN_PASSWORD: "19990220"
          PERSONAL_GITHUB_ACCESS_TOKEN: "${{ secrets.PERSONAL_GITHUB_ACCESS_TOKEN }}"
          USERNAME: "HikaruOhtaki"
          MATCH_PASSWORD: '${{ secrets.MATCH_PASSWORD }}'
        run: |
          echo "$(ls /Users/runner/Library/Developer/)"
          fastlane beta
