name: CICD

on:
  workflow_dispatch:

env:
  DEVELOPER_DIR: /Applications/Xcode_13.2.1.app

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: ls directory
        run: ls ~/Library/Developer/Xcode/DerivedData

      - uses: actions/checkout@v2
      - name: Deploy Testflight
        env:
          MATCH_KEYCHAIN_NAME: "KEYCHAIN"
          MATCH_KEYCHAIN_PASSWORD: "19990220"
          PERSONAL_GITHUB_ACCESS_TOKEN: "${{ secrets.PERSONAL_GITHUB_ACCESS_TOKEN }}"
          USERNAME: "HikaruOhtaki"
          MATCH_PASSWORD: '${{ secrets.MATCH_PASSWORD }}'
        run: fastlane beta
