name: CICD

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v2

      - name: create AppStoreConnect AuthKey
        run: |
          mkdir ~/private_keys; echo "${{ secrets.ASC_API_KEY }}" | base64 -d > ~/private_keys/AuthKey_$ASC_KEY_ID.p8

      - name: Deploy Testflight
        env:
          MATCH_KEYCHAIN_NAME: "KEYCHAIN"
          MATCH_KEYCHAIN_PASSWORD: "19990220"
          PERSONAL_GITHUB_ACCESS_TOKEN: "${{ secrets.PERSONAL_GITHUB_ACCESS_TOKEN }}"
          USERNAME: "HikaruOhtaki"
          MATCH_PASSWORD: '${{ secrets.MATCH_PASSWORD }}'
        run: fastlane beta
